### PR TITLE
RunTests: use test label number instead of counter

### PR DESCRIPTION
**Pull request by albietz**
In the testing logs (e.g. in Travis), this shows the test label shown in the comment above each test, rather than just a counter. For instance, the logs will show 175 for the test labeled `# Test 175:`, instead of the value of the counter. This avoids weird discrepancies when reading the Travis logs.

cc @yannstad

### CODE REVIEW

**Comment by yannstad** [comment]
LGTM.
Thanks!

**Comment by JohnLangford** [comment]
@arielf any comments?

**Comment by yannstad** [comment]
At least it would be good to update the RunTests doc (line ~750 in the RunTests file).

**Comment by jackgerrits** [comment]
@JohnLangford are we able to get this in?

**Comment by JohnLangford** [comment]
Yes, let's merge.

**Comment by JohnLangford** [comment]
That seems plausible as there is no need to be over-specific.  Send a pull request?

**Pull request merged**
