### PR TITLE
[audit] Make sure --audit output is reproducible across systems.

### PR DESCRIPTION
**Pull request by kumpera**
Interactions output was using std::sort which triggered issues when values were the same.

### CODE REVIEW

**Comment by kumpera** [comment]
This fixes a bug I found while working on #1746

**Comment by JohnLangford** [comment]
This looks good, but appveyor is barfing on 176?

**Comment by kumpera** [comment]
Investigating it next.

**Comment by kumpera** [comment]
The appveyor failure was due to some technical debt in our test harness. I added an issue to track this: https://github.com/VowpalWabbit/vowpal_wabbit/issues/1803

**Pull request merged**
