### PR TITLE
coin weights fix

### PR DESCRIPTION
**Pull request by ataymano**
If we are using coin for any regression, weights in the model are not giving us predictions that converge to observed costs, but have some constant multiplier (weighted average of all examples squared norms).
Proof:
```
def generate(fname, count):
    with open(fname, 'w') as f:
        for i in range(count):
            f.write('2:0.5 | f1 f2 f3\n')

generate('data.txt', 1000000)

vw -d data.txt --invert_hash model_no_coin.txt
vw -d data.txt --coin --invert_hash model_coin.txt

model_no_coin.txt:
f2:82936:0.5
Constant:116060:0.5
f3:222792:0.5
f1:259761:0.5

0.5 + 0.5 + 0.5 + 0.5 = 2

model_coin.txt:
:82936:2
:116060:2
:222792:2
:259761:2

2 + 2 + 2 + 2 = 8

```

Reason for that is the following:
coin is implemented as mode of ftrl, and there are 2 predict methods are used here:
[ftrl::predict](https://github.com/VowpalWabbit/vowpal_wabbit/blob/f105fbf26c9bcc0025fd2547299db67144201a79/vowpalwabbit/ftrl.cc#L77) (which is pretty much GD::predict)
[coin_betting_predict](https://github.com/VowpalWabbit/vowpal_wabbit/blob/f105fbf26c9bcc0025fd2547299db67144201a79/vowpalwabbit/ftrl.cc#L209) - which is used only inside learn_coin_betting and expected to return unnormalized prediction (according to [this](https://github.com/VowpalWabbit/vowpal_wabbit/blob/f105fbf26c9bcc0025fd2547299db67144201a79/vowpalwabbit/ftrl.cc#L219))

So every stack that is relying on predictions from base::predict has to deal with scaled predictions (and may fail if it relies on them to converge to logged costs, like #2834).

Here is quick patch which is about explicitly normalizing prediction before returning from ftrl::predict.
Still looking how to do it properly, but please let me know if you have suggestions.

@bremen79, it would be amazing if you can take a look and suggest something here (or is there a paper with details of this algorithm variation exists somewhere?).

### CODE REVIEW

**Comment by ataymano** [comment]
This diff is completely fixing example reported in #2834.

Results on cbified 500 OpenML classification data sets:

1) Epsilon-greedy + coin
image

2) SquareCB + coin
image

3) Bagging + coin
image

4) Softmax + coin
image

5) Synthcover + coin
image

6) Cover + coin
image


So, cover and synthcover got better, but is not fixed completely. Looking more into it.

**Comment by bremen79** [comment]
Hi, I'll try to take a look this weekend.

**Comment by bremen79** [comment]
I have taken a look at the code: the change looks good to me.
Regarding the source of this algorithm: there is no paper for this variation. The main algorithm is COCOB (that is published), but then there are a bunch of tricks: monitoring the range of the samples, the Lipschitz constant and the normalization you fixed. The normalization actually comes from the code of John of SGD: I added it because empirically it improved the performance, but I don't have a clear reason on why this is a good idea...

**Comment by ataymano** [comment]
> I have taken a look at the code: the change looks good to me.
> Regarding the source of this algorithm: there is no paper for this variation. The main algorithm is COCOB (that is published), but then there are a bunch of tricks: monitoring the range of the samples, the Lipschitz constant and the normalization you fixed. The normalization actually comes from the code of John of SGD: I added it because empirically it improved the performance, but I don't have a clear reason on why this is a good idea...

Thank you for reviewing!
Some tests are failing (because of changed stdout) - still going to double check that there is nothing wrong with them and will merge later this week.

**Review by jackgerrits — APPROVED** [review]

**Comment by ataymano** [comment]
Fixes #2834

**Pull request merged**
