### PR TITLE
Fix weighted average on cluster mode

### LINKED ISSUE #1771: Not same model weight from nodes on cluster mode
#### Describe the bug
I run VW 8.6.1 with some large dataset on cluster mode, models from each node are not exactly same, but I didn't have this problem with VW 7.7.

#### To Reproduce
For convenience, here I use some toy examples to reproduce this bug.

Here is my workspace,
```
.
├── bin
│   ├── spanning_tree-7.7.macOS
│   ├── spanning_tree-8.6.1.macOS
│   ├── vw-7.7.macOS
│   └── vw-8.6.1.macOS
├── data
│   ├── train.vw.0
│   └── train.vw.1
├── log
│   ├── spanning_tree.7.7.log
│   ├── spanning_tree.8.6.1.log
│   ├── train-7.7-0.log
│   ├── train-7.7-1.log
│   ├── train-8.6.1-0.log
│   └── train-8.6.1-1.log
├── model
    ├── vwmodel.7.7.0.txt
    ├── vwmodel.7.7.1.txt
    ├── vwmodel.8.6.1.0.txt
    └── vwmodel.8.6.1.1.txt
```

I built the binary file for `vw` and `spanning_tree` with release **8.6.1** and **7.7**, then place then in `bin` folder.

`data` contains 2 input file for 2 nodes.
- train.vw.0
```
1.0 |a big long |b bad
-1.0 |a small |b average    
```

- train.vw.1
```
1.0 |a short |b good
-1.0 |a median
```

The script I used to train is,
```bash
VW_VERSION="8.6.1"

bin/spanning_tree-$VW_VERSION.macOS &> log/spanning_tree.$VW_VERSION.log &

for i in {0..1}
do
    bin/vw-$VW_VERSION.macOS -d data/train.vw.$i \
    --readable_model model/vwmodel.$VW_VERSION.$i.txt \
    -q ab \
    --span_server localhost --total 2 --node $i --unique_id 2666 \
    --passes 1 --holdout_off &> log/train-$VW_VERSION-$i.log &
done
```

With VW 8.6.1, I got different readable models,
**vwmodel.8.6.1.0.txt**
```
1000:-0.15735
8068:0.11768
25745:0.11768
53501:0.158008
67504:0.158008
73913:0.11768
81463:-0.15735
116060:-0.00945443
118687:0.158008
151495:0.11768
171199:0.11768
202767:-0.15735
```
**vwmodel.8.6.1.1.txt**
```
1000:-0.15735
8068:0.11768
25745:0.11768
53501:0.158008
67504:0.158008
73913:0.11768
81463:-0.15735
116060:-0.00945443
118687:0.158008
160265:-0.233727
```

But with VW 7.7, I could get exactly same models,
**vwmodel.7.7.0.txt**
```
1000:-0.157350
8068:0.117680
25745:0.117680
31359:-0.157350
53501:0.158008
73913:0.117680
81463:-0.157350
106193:0.117680
116060:-0.009454
118687:0.158008
127577:0.117680
140576:0.158008
160265:-0.233727
```
**vwmodel.7.7.1.txt**
```
1000:-0.157350
8068:0.117680
25745:0.117680
31359:-0.157350
53501:0.158008
73913:0.117680
81463:-0.157350
106193:0.117680
116060:-0.009454
118687:0.158008
127577:0.117680
140576:0.158008
160265:-0.233727
```

#### Expected behavior
The models from each node should be same.

#### Observed Behavior
With VW 8.6.1, I cannot get the same model from each node.

Also, I found with this toy example or the large dataset I used, `vw` can **always** average the feature value with hash code in the first half (0~2^17) of hashing space we used (2^18 in toy example), it seems to be a bug related to bit operation?

#### Environment
VW: `7.7` and `8.6.1`
OS: macOS and linux

Thank!

### PR DESCRIPTION
**Pull request by silverguo**
Fix #1771 

After some investigations, I think this issue might be caused by wrong stride size when averaging the weights in `accumulate_weighted_avg`. A simple fix here might be enough.

What do you think about?

### CODE REVIEW

**Comment by JohnLangford** [comment]
Good find!  The previous usage looks inherently buggy.

**Comment by JohnLangford** [comment]
Is it possible to add a small test case to RunTests to prevent future regressions?

**Comment by silverguo** [comment]
> Is it possible to add a small test case to RunTests to prevent future regressions?

Sure, it seems that I need to prepare a separate .sh file (run 2 vw process and compare their models) and run it in RunTests.

Because I need cluster mode, do you know how could I run a spanning_tree in RunTests?

**Comment by JohnLangford** [comment]
You should be able to just create a script along the lines of single machine (https://github.com/VowpalWabbit/vowpal_wabbit/blob/master/cluster/single_machine ) ---a few of the tests have this flavor.

**Comment by silverguo** [comment]
@JohnLangford I add a simple test to check whether it has same model from all nodes on cluster mode, please take a look at it.

**Comment by JohnLangford** [comment]
Great, merged.  Thanks :-)

**Comment by arielf** [comment]
Thanks @silverguo !

**Pull request merged**
