### PR TITLE
Fix build scripts for python3 on linux

### PR DESCRIPTION
**Pull request by peterychang**

### CODE REVIEW

**Comment by peterychang** [comment]
Fix confirmed Python2.7 on Boost1.64, python3.6 on Boost1.64, and python3.7 on Boost1.67

**Comment by kumpera** [comment]
This broke windows :(

**Comment by peterychang** [comment]
Found a bug with python 2.7 and boost 1.67

**Comment by jackgerrits** [comment]
Thanks!

**Comment by n17s** [comment]
This fixed my issues with successfully compiling but not being able to import pyvw (tested on python 3.7)

**Comment by peterychang** [comment]
@n17s what is the error you're getting?

**Pull request merged**
