### PR TITLE
Unit tests dynamically link to libvw, so they can't catch vw specific exceptions. See #2234.

### PR DESCRIPTION
**Pull request by kumpera**
This fixes a failing test on OSX with recent clang that enforces visibility rules to classes as well.

### CODE REVIEW

**Comment by kumpera** [comment]
Linux failure is due to maven https issue.

**Comment by kumpera** [comment]
This is the proper fix instead of just hacking around the test.

**Comment by jackgerrits** [comment]
Didn't we set default visibility to hidden though?

**Comment by jackgerrits** [comment]
@kumpera looks like there are issues on Windows?

**Comment by kumpera** [comment]
Fixed the windows issue.

**Pull request merged**
