### PR TITLE
Coin betting

### PR DESCRIPTION
**Pull request by bremen79**
I have implement the coin betting algorithm.

The algorithm used is the one in COCOB paper, with a different methodology to deal with increasing Lipschitz constants. This approach seems to be the best one among the ones I tried.

Note that the default alpha and beta parameters are good for the logistic loss, while for the square loss they must be bigger, like 16 and 4 respectively. 

Note that there is no "subtraction of the mean" here, it is still unclear how to run that efficiently.

### CODE REVIEW

**Comment by JohnLangford** [comment]
Can you add a test case for it as well?

**Comment by bremen79** [comment]
I added the train/test files.
I was adding the save/resume test as well, but it fails, as it fails for FTRL-Proximal as well. Is it a known issue with the save of FTRL models?

**Comment by JohnLangford** [comment]
I vaguely recall "yes", but perhaps you can fix it?

**Comment by bremen79** [comment]
Let me try

**Comment by JohnLangford** [comment]
This: https://github.com/VowpalWabbit/vowpal_wabbit/blob/master/test/save_resume_test.py#L156 
says that the save_resume failure is a known issue.  

However, it's not essential for this patch, so I'll merge and open an issue.  If you can fix it tomorrow, just send a separate pull request.

**Comment by bremen79** [comment]
Sounds good

**Pull request merged**
