### PR TITLE
VS 2017 fixes

### PR DESCRIPTION
**Pull request by skofsky**
PR to fix a compile issue on VS 2017 and fix some issues I noticed reviewing the code.

### CODE REVIEW

**Comment by JohnLangford** [comment]
The build is breaking.    Fixable?

**Comment by jackgerrits** [comment]
LGTM

**Comment by JohnLangford** [comment]
@rajan-chari can you take a look?

**Comment by rajan-chari** [comment]
looking

**Comment by rajan-chari** [comment]
Looks good.  Thanks.

**Comment by JohnLangford** [comment]
Merged, thanks :-)

**Pull request merged**
