### PR TITLE
[Java] Support loading the VW JNI library from JAR file.

### PR DESCRIPTION
**Pull request by zwd-ms**
For Java API, the native library is packed inside the JAR file, but it is not loaded. Instead, the code tries to load the JNI lib from `java.library.path`. This PR adds loading from JAR for the Java API, which is already used in the spark API.

- move the native lib loader to a common package
- add loading from JAR in case the JNI lib is not found in java.library.path

Resolves issue #1579 (for linux_64).

### CODE REVIEW

**Comment by jackgerrits** [comment]
So this resolves lib loading for the original java bindings on linux only right? We'll need to add a bit more for macos and windows?

**Comment by zwd-ms** [comment]
That's right, the lib loader hardcodes the directory for linux_64, `natives/linux_64/libvw_jni.so`. MacOS and Win still need to manually specify the `java.library.path` for now.

Also, the published jar only has linux_64 lib. We haven't changed that if there is a plan.

**Comment by zwd-ms** [comment]
Actually the windows build is [unsupported](https://github.com/VowpalWabbit/vowpal_wabbit/blob/e53b3a0d9e354427977a10d190b9b59d0132937b/CMakeLists.txt#L105). (Is there a reason?)

**Comment by jackgerrits** [comment]
It's only unsupported as we havent had the time to make it work.

Some of the tests are not working on MacOS so I think we need to fix them before we can enable it

**Review by jackgerrits — APPROVED** [review]

**Pull request merged**
