### PR TITLE
Add test for interact reduction

### PR DESCRIPTION
**Pull request by jackgerrits**

### CODE REVIEW

**Review by olgavrou — COMMENTED** [review]
Is it worth checking the interactions by using --invert_hash?

**Comment by jackgerrits** [comment]
This doesn't add interactions in that sense - but it adds new features. So maybe a readable model here is a good idea?

**Comment by olgavrou** [comment]
> This doesn't add interactions in that sense - but it adds new features. So maybe a readable model here is a good idea?

Yeah my understanding of `--invert_hash` is that it's the same as `--readable_model` but instead of hashes and weights it gives use user-readable features and weights. I guess either would do

**Comment by jackgerrits** [comment]
Added readable model

**Review by olgavrou — APPROVED** [review]

**Pull request merged**
