### PR TITLE
[BUG_FIX] Fixes Visibility Issues And CMakeLists.txt Error For Tests

### LINKED ISSUE #2242: 8.8.0 build fails with -Wl,--no-undefined linker flag
vw 8.8.0 build fails with -Wl,--no-undefined linker flag in current Mageia Cauldron (the development version):
```
$ gcc --version
gcc (Mageia 9.2.1-0.20200201.1.mga8) 9.2.1 20200201

$ cmake --version
cmake version 3.16.3
```
```
[ 75%] Linking CXX shared library libvw.so
cd /builddir/build/BUILD/vowpal_wabbit-8.8.0/build/vowpalwabbit && /usr/bin/cmake -E cmake_link_script CMakeFiles/vw.dir/link.txt --verbose=1
/usr/bin/c++ -fPIC -O2 -g -pipe -Wformat -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fstack-protector --param=ssp-buffer-size=4 -fasynchronous-unwind-tables -DNDEBUG -Wl,--as-needed -Wl,--no-undefined -Wl,-z,relro -Wl,-O1 -Wl,--build-id -Wl,--enable-new-dtags -shared -Wl,-soname,libvw.so -o libvw.so CMakeFiles/vw.dir/accumulate.cc.o CMakeFiles/vw.dir/action_score.cc.o CMakeFiles/vw.dir/active_cover.cc.o CMakeFiles/vw.dir/active.cc.o CMakeFiles/vw.dir/audit_regressor.cc.o CMakeFiles/vw.dir/autolink.cc.o CMakeFiles/vw.dir/baseline.cc.o CMakeFiles/vw.dir/best_constant.cc.o CMakeFiles/vw.dir/bfgs.cc.o CMakeFiles/vw.dir/binary.cc.o CMakeFiles/vw.dir/boosting.cc.o CMakeFiles/vw.dir/bs.cc.o CMakeFiles/vw.dir/cache.cc.o CMakeFiles/vw.dir/cb_adf.cc.o CMakeFiles/vw.dir/cb_algs.cc.o CMakeFiles/vw.dir/cb_explore_adf_bag.cc.o CMakeFiles/vw.dir/cb_explore_adf_cover.cc.o CMakeFiles/vw.dir/cb_explore_adf_first.cc.o CMakeFiles/vw.dir/cb_explore_adf_greedy.cc.o CMakeFiles/vw.dir/cb_explore_adf_regcb.cc.o CMakeFiles/vw.dir/cb_explore_adf_softmax.cc.o CMakeFiles/vw.dir/cb_explore.cc.o CMakeFiles/vw.dir/cb_sample.cc.o CMakeFiles/vw.dir/cb.cc.o CMakeFiles/vw.dir/cbify.cc.o CMakeFiles/vw.dir/ccb_label.cc.o CMakeFiles/vw.dir/classweight.cc.o CMakeFiles/vw.dir/comp_io.cc.o CMakeFiles/vw.dir/conditional_contextual_bandit.cc.o CMakeFiles/vw.dir/confidence.cc.o CMakeFiles/vw.dir/cost_sensitive.cc.o CMakeFiles/vw.dir/cs_active.cc.o CMakeFiles/vw.dir/csoaa.cc.o CMakeFiles/vw.dir/ect.cc.o CMakeFiles/vw.dir/example.cc.o CMakeFiles/vw.dir/explore_eval.cc.o CMakeFiles/vw.dir/ftrl.cc.o CMakeFiles/vw.dir/gd_mf.cc.o CMakeFiles/vw.dir/gd.cc.o CMakeFiles/vw.dir/gen_cs_example.cc.o CMakeFiles/vw.dir/global_data.cc.o CMakeFiles/vw.dir/interact.cc.o CMakeFiles/vw.dir/interactions.cc.o CMakeFiles/vw.dir/io_buf.cc.o CMakeFiles/vw.dir/kernel_svm.cc.o CMakeFiles/vw.dir/label_dictionary.cc.o CMakeFiles/vw.dir/lda_core.cc.o CMakeFiles/vw.dir/learner.cc.o CMakeFiles/vw.dir/log_multi.cc.o CMakeFiles/vw.dir/loss_functions.cc.o CMakeFiles/vw.dir/lrq.cc.o CMakeFiles/vw.dir/lrqfa.cc.o CMakeFiles/vw.dir/marginal.cc.o CMakeFiles/vw.dir/memory_tree.cc.o CMakeFiles/vw.dir/mf.cc.o CMakeFiles/vw.dir/multiclass.cc.o CMakeFiles/vw.dir/multilabel_oaa.cc.o CMakeFiles/vw.dir/multilabel.cc.o CMakeFiles/vw.dir/mwt.cc.o CMakeFiles/vw.dir/network.cc.o CMakeFiles/vw.dir/nn.cc.o CMakeFiles/vw.dir/no_label.cc.o CMakeFiles/vw.dir/noop.cc.o CMakeFiles/vw.dir/oaa.cc.o CMakeFiles/vw.dir/OjaNewton.cc.o CMakeFiles/vw.dir/options_boost_po.cc.o CMakeFiles/vw.dir/options_serializer_boost_po.cc.o CMakeFiles/vw.dir/parse_args.cc.o CMakeFiles/vw.dir/parse_example.cc.o CMakeFiles/vw.dir/parse_primitives.cc.o CMakeFiles/vw.dir/parse_regressor.cc.o CMakeFiles/vw.dir/parser.cc.o CMakeFiles/vw.dir/print.cc.o CMakeFiles/vw.dir/rand48.cc.o CMakeFiles/vw.dir/recall_tree.cc.o CMakeFiles/vw.dir/scorer.cc.o CMakeFiles/vw.dir/search_dep_parser.cc.o CMakeFiles/vw.dir/search_entityrelationtask.cc.o CMakeFiles/vw.dir/search_graph.cc.o CMakeFiles/vw.dir/search_hooktask.cc.o CMakeFiles/vw.dir/search_meta.cc.o CMakeFiles/vw.dir/search_multiclasstask.cc.o CMakeFiles/vw.dir/search_sequencetask.cc.o CMakeFiles/vw.dir/search.cc.o CMakeFiles/vw.dir/sender.cc.o CMakeFiles/vw.dir/shared_feature_merger.cc.o CMakeFiles/vw.dir/simple_label.cc.o CMakeFiles/vw.dir/stagewise_poly.cc.o CMakeFiles/vw.dir/svrg.cc.o CMakeFiles/vw.dir/topk.cc.o CMakeFiles/vw.dir/unique_sort.cc.o CMakeFiles/vw.dir/version.cc.o CMakeFiles/vw.dir/vw_exception.cc.o CMakeFiles/vw.dir/vw_validate.cc.o CMakeFiles/vw.dir/warm_cb.cc.o  -Wl,-rpath,/builddir/build/BUILD/vowpal_wabbit-8.8.0/build/vowpalwabbit: liballreduce.so /usr/lib64/libboost_program_options.so.1.72.0 -ldl /usr/lib64/libz.so -pthread 
make[2]: Leaving directory '/builddir/build/BUILD/vowpal_wabbit-8.8.0/build'
/usr/bin/ld: CMakeFiles/vw.dir/accumulate.cc.o: in function `void AllReduceSockets::all_reduce<float, &(add_float(float&, float const&))>(float*, unsigned long)':
/builddir/build/BUILD/vowpal_wabbit-8.8.0/vowpalwabbit/allreduce.h:302: undefined reference to `AllReduceSockets::all_reduce_init()'
/usr/bin/ld: CMakeFiles/vw.dir/accumulate.cc.o: in function `void AllReduceThreads::all_reduce<float, &(add_float(float&, float const&))>(float*, unsigned long)':
/builddir/build/BUILD/vowpal_wabbit-8.8.0/vowpalwabbit/allreduce.h:141: undefined reference to `AllReduceSync::waitForSynchronization()'
/usr/bin/ld: CMakeFiles/vw.dir/accumulate.cc.o: in function `void AllReduceSockets::all_reduce<float, &(add_float(float&, float const&))>(float*, unsigned long)':
/builddir/build/BUILD/vowpal_wabbit-8.8.0/vowpalwabbit/allreduce.h:304: undefined reference to `AllReduceSockets::broadcast(char*, unsigned long)'
/usr/bin/ld: CMakeFiles/vw.dir/accumulate.cc.o: in function `void AllReduceThreads::all_reduce<float, &(add_float(float&, float const&))>(float*, unsigned long)':
/builddir/build/BUILD/vowpal_wabbit-8.8.0/vowpalwabbit/allreduce.h:175: undefined reference to `AllReduceSync::waitForSynchronization()'
/usr/bin/ld: CMakeFiles/vw.dir/kernel_svm.cc.o: in function `void AllReduceThreads::all_reduce<unsigned long, &(add_size_t(unsigned long&, unsigned long const&))>(unsigned long*, unsigned long)':
/builddir/build/BUILD/vowpal_wabbit-8.8.0/vowpalwabbit/allreduce.h:141: undefined reference to `AllReduceSync::waitForSynchronization()'
/usr/bin/ld: CMakeFiles/vw.dir/kernel_svm.cc.o: in function `void AllReduceSockets::all_reduce<unsigned long, &(add_size_t(unsigned long&, unsigned long const&))>(unsigned long*, unsigned long)':
/builddir/build/BUILD/vowpal_wabbit-8.8.0/vowpalwabbit/allreduce.h:302: undefined reference to `AllReduceSockets::all_reduce_init()'
/usr/bin/ld: /builddir/build/BUILD/vowpal_wabbit-8.8.0/vowpalwabbit/allreduce.h:304: undefined reference to `AllReduceSockets::broadcast(char*, unsigned long)'
/usr/bin/ld: CMakeFiles/vw.dir/kernel_svm.cc.o: in function `void AllReduceThreads::all_reduce<char, &(copy_char(char&, char const&))>(char*, unsigned long)':
/builddir/build/BUILD/vowpal_wabbit-8.8.0/vowpalwabbit/allreduce.h:141: undefined reference to `AllReduceSync::waitForSynchronization()'
/usr/bin/ld: /builddir/build/BUILD/vowpal_wabbit-8.8.0/vowpalwabbit/allreduce.h:175: undefined reference to `AllReduceSync::waitForSynchronization()'
/usr/bin/ld: CMakeFiles/vw.dir/kernel_svm.cc.o: in function `void AllReduceThreads::all_reduce<unsigned long, &(add_size_t(unsigned long&, unsigned long const&))>(unsigned long*, unsigned long)':
/builddir/build/BUILD/vowpal_wabbit-8.8.0/vowpalwabbit/allreduce.h:175: undefined reference to `AllReduceSync::waitForSynchronization()'
/usr/bin/ld: CMakeFiles/vw.dir/kernel_svm.cc.o: in function `void AllReduceSockets::all_reduce<char, &(copy_char(char&, char const&))>(char*, unsigned long)':
/builddir/build/BUILD/vowpal_wabbit-8.8.0/vowpalwabbit/allreduce.h:302: undefined reference to `AllReduceSockets::all_reduce_init()'
/usr/bin/ld: /builddir/build/BUILD/vowpal_wabbit-8.8.0/vowpalwabbit/allreduce.h:304: undefined reference to `AllReduceSockets::broadcast(char*, unsigned long)'
/usr/bin/ld: CMakeFiles/vw.dir/stagewise_poly.cc.o: in function `void AllReduceThreads::all_reduce<unsigned char, &(reduce_min_max(unsigned char&, unsigned char const&))>(unsigned char*, unsigned long)':
/builddir/build/BUILD/vowpal_wabbit-8.8.0/vowpalwabbit/allreduce.h:141: undefined reference to `AllReduceSync::waitForSynchronization()'
/usr/bin/ld: CMakeFiles/vw.dir/stagewise_poly.cc.o: in function `void AllReduceSockets::all_reduce<unsigned char, &(reduce_min_max(unsigned char&, unsigned char const&))>(unsigned char*, unsigned long)':
/builddir/build/BUILD/vowpal_wabbit-8.8.0/vowpalwabbit/allreduce.h:302: undefined reference to `AllReduceSockets::all_reduce_init()'
/usr/bin/ld: /builddir/build/BUILD/vowpal_wabbit-8.8.0/vowpalwabbit/allreduce.h:304: undefined reference to `AllReduceSockets::broadcast(char*, unsigned long)'
/usr/bin/ld: CMakeFiles/vw.dir/stagewise_poly.cc.o: in function `void AllReduceThreads::all_reduce<unsigned char, &(reduce_min_max(unsigned char&, unsigned char const&))>(unsigned char*, unsigned long)':
/builddir/build/BUILD/vowpal_wabbit-8.8.0/vowpalwabbit/allreduce.h:175: undefined reference to `AllReduceSync::waitForSynchronization()'
collect2: error: ld returned 1 exit status
```

### PR DESCRIPTION
**Pull request by thealphadollar**
The Pull Request updates a major part of the code. The PR brings in the following changes:

- fix missing boost library requirement of `program_options`.

Screenshot from 2020-03-21 18-51-44

- fix visibility issues leading to "undefined reference" errors.

Below are the few of the screenshots of the issues that were fixed. This does not include all since that would be too much to analyze.

Screenshot from 2020-03-21 17-04-34

Screenshot from 2020-03-21 17-11-54

Screenshot from 2020-03-21 17-12-31

Screenshot from 2020-03-21 17-27-14

Screenshot from 2020-03-21 17-53-59

Once the changes are merged, the `master` could be built with the below mentioned GCC and CMake on Ubuntu 18.04. 

```
gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
cmake version 3.10.2
```

@wally-mageia Can you please test it on Mageia? I've destroyed the VM I created earlier :disappointed: 

fixes #2242

### CODE REVIEW

**Comment by thealphadollar** [comment]
@jackgerrits @kumpera Why do you think the builds are failing?

Also, my sincere apologies if I've done this a wrong way since I do not have much experience with C/C++ sources. I would like to know if there are better ways to do that same without changing so many source files.

**Comment by wally-mageia** [comment]
> @wally-mageia Can you please test it on Mageia? I've destroyed the VM I created earlier

I can confirm that the build succeeds with the same steps mentioned in https://github.com/VowpalWabbit/vowpal_wabbit/issues/2242#issuecomment-602014215.

**Comment by thealphadollar** [comment]
Sounds good. Thanks a lot.

**Comment by jackgerrits** [comment]
@thealphadollar this is failing to build on CI, can you please take a look?

**Comment by thealphadollar** [comment]
@jackgerrits I'm unable to understand why the build is failing, and I'd need your help.

**Comment by jackgerrits** [comment]
Feel free to push commits to try code using the CI. You should know if it worked or didn't within a couple of minutes

- Try using a compiler version that the test suite is using, you may be using too recent of compiler that has added compatability.
- Ensure the header is included where it needs to be
- I think the syntax for specifying attributes on namespaces is to put them after the namespace name https://en.cppreference.com/w/cpp/language/namespace

**Comment by jackgerrits** [comment]
Hi @thealphadollar. This has been dormant for a while, are you still interested in working on this? If I don't hear from you I am going to go ahead and close it in 7 days.

**Pull request closed without merging**
