### PR TITLE
Update assembly versions to match current version

### PR DESCRIPTION
**Pull request by jackgerrits**

### CODE REVIEW

**Comment by JohnLangford** [comment]
This will be a chronic problem.  Is there any way to make it automatic?

**Comment by kumpera** [comment]
> This action should be done as part of the change when we bump the version number in the future

Tracking this issue here: https://github.com/VowpalWabbit/vowpal_wabbit/projects/5#card-16435167

**Comment by JohnLangford** [comment]
Ok.  /utl/new_version is where something like an existing release script lives.

**Comment by JohnLangford** [comment]
Merged, thanks both :-)

**Pull request merged**
