### PR TITLE
Fixes test failure in test_pyvw.py

### PR DESCRIPTION
**Pull request by Smit-create**
* python
  * Fixes test failure in test_pyvw.py when ran locally

### CODE REVIEW

**Comment by jackgerrits** [comment]
I'm not sure what your test failure was locally, but deleting the data file won't fix it. You'll notice that CI is failing for this PR. Perhaps you need to check if the file exists before trying to delete it?

**Comment by Smit-create** [comment]
I had following test failure before the change I commited:
```
===================================================== FAILURES =====================================================
_______________________________________________ test_regressor_args ________________________________________________

    def test_regressor_args():
        # load and parse external data file
        data_file = os.path.join(os.path.dirname(os.path.realpath(__file__)), 'resources', 'train.dat')
        model = vw(oaa=3, data=data_file, passes=30, c=True, k=True)
        assert model.predict('| feature1:2.5') == 1

        # update model in memory
        for _ in range(10):
            model.learn('3 | feature1:2.5')

        assert model.predict('| feature1:2.5') == 3

        # save model
        model.save('tmp.model')
        del model

        # load initial regressor and confirm updated prediction
        new_model = vw(i='tmp.model', quiet=True)
        assert new_model.predict('| feature1:2.5') == 3
        del new_model

        # clean up
>       os.remove('{}.cache'.format(data_file))
E       FileNotFoundError: [Errno 2] No such file or directory: '/home/smit/Smit Lunagariya/vowpal_wabbit/python/tes
ts/resources/train.dat.cache'
```

**Comment by Smit-create** [comment]
> Perhaps you need to check if the file exists before trying to delete it

It exists in my branch

**Comment by jackgerrits** [comment]
File existing as in on disk and not the file being checked into the repo. Deleting the data file is not the right thing to do here.

**Comment by Smit-create** [comment]
Okay got it. Should I close it then?

**Comment by jackgerrits** [comment]
I think either close it or add an existence check

**Pull request closed without merging**
