### PR TITLE
Add script to replay dsjson logs against a known start model

### PR DESCRIPTION
**Pull request by jackgerrits**
- Script is used to replay dsjson logs against a known start model and compares model hash

### CODE REVIEW

**Comment by JohnLangford** [comment]
This pull request **introduces 2 alerts** when merging cb9782391dded4b74d20e11e89e55a65393ffc55 into 17ae1cde478405fdd794d24d4f33cc334d69d7ea - [view on LGTM.com](https://lgtm.com/projects/g/VowpalWabbit/vowpal_wabbit/rev/pr-782a30acc1864b453394e2c52357c3e3314a5a4d)

**new alerts:**

* 1 for Unused local variable
* 1 for Unused import

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by marco-rossi29** [comment]
Should this live in reinforcement_learning repo, rather than on VW?

**Comment by jackgerrits** [comment]
Good point, yes I think it makes more sense in the rl repo

**Comment by jackgerrits** [comment]
Moved to other repo VowpalWabbit/reinforcement_learning#65

**Pull request closed without merging**
