### PR TITLE
Consume RapidJson through submodule

### LINKED ISSUE #1689: Remove rapidjson from repo
Rapidjson should either be consumed by a submodule or through a package manager like apt-get

### PR DESCRIPTION
**Pull request by jackgerrits**
- Rapidjson is now consumed as a submodule at v1.1.0
- When using CMake the submodule is automatically checked out if it isn't already there
- When using VisualStudio the submodule must be explicitly checked out

Fixes #1689

### CODE REVIEW

**Comment by jackgerrits** [comment]
Running a CI image update now, once that's done I will be able to fix the travis build

**Comment by jackgerrits** [comment]
It seems the apt-get package isn't available on 14.04. Perhaps this should be done through a submodule instead then

**Comment by jackgerrits** [comment]
Guidance on the project website is to just copy the `rapidjson/include` directory. So perhaps as a good first effort we can simply remove all of the extra files that don't need to be there?

**Comment by kumpera** [comment]
Wasn't the idea to consume it through a submodule?

**Comment by jackgerrits** [comment]
You're right, was hoping we could do it a little easier with packages but it doesn't seem like the way to go

**Comment by lokitoth** [comment]
+40 -53113

^ The best kind of code change

Are we also upgrading the version here, or is it a like-for-like substitution?

**Comment by jackgerrits** [comment]
It's tricky to know, I am targeting the last released version which was in 2016... It seems like we were on something like that as well in the source.

**Comment by lokitoth** [comment]
We may want to do a manual test pass around good and bad input, and/or make a smoke-test?

**Comment by jackgerrits** [comment]
A few of our tests go through json parsing, but yes there is potential for issues if behavior changed. It seems like versioning is not very good on Rapidjson but I think we are on the same major and minor version

**Comment by lokitoth** [comment]
Okay, that seems reasonable. Expectation should be that if major/minor remain constant, behaviour should be the same up to bug fixes.

**Comment by jackgerrits** [comment]
Just diffed the submodule against the old checked in source and the only changes are whitespace as far as I can tell

**Comment by JohnLangford** [comment]
We should merge as soon as tests pass.

**Comment by JohnLangford** [comment]
This seems to be causing issues with lgtm that would be good to fix.  https://lgtm.com/projects/g/VowpalWabbit/vowpal_wabbit/logs/rev/pr-9c14123a062578394b2332b974752376dc9fc6a0/lang:cpp/stage:Build%20merge_78d7529bf560c71feaef2324f27ffb47a1a9d50c

**Comment by jackgerrits** [comment]
The LGTM failure is a known issue and will be resolved when we merge the PR. See this forum post for details: https://discuss.lgtm.com/t/git-submodule-sync-missing/1989

**Pull request merged**
