### PR TITLE
[WIP] Draft extending vw-hyperopt to CB algorithm

### PR DESCRIPTION
**Pull request by adityauser**
Currently, `vw-hyperopt.py` do not support cb, cb_explore and cb_explore_adf. This PR will take care of that

- [ ] TODO: Complete plotting and validation_metric function.
- [ ] TODO: Add option: cb, cb_explore and cb_explore_adf 
- [ ] TODO: Add option for cb_type
- [x] TODO: Take care that arguments for both cb and non-cb are not provided at the same time
- [ ] TODO: Training and testing for multiple seeds

### CODE REVIEW

**Comment by adityauser** [comment]
@kirillfish what is your opinion on this?

**Comment by adityauser** [comment]
I'm currently working on some other projects, I won't be able to work in this PR. Do you want me to close this?

**Comment by jackgerrits** [comment]
If you're still working on it, then you can definitely keep it open!

**Comment by jackgerrits** [comment]
Hey @adityauser we are getting ready for a release soon, if you'd like to get this into the release let me know.

**Comment by adityauser** [comment]
I don't think so I could get it done in the coming weeks.
I'm very much engaged in other stuffs till August.

**Comment by jackgerrits** [comment]
Okay no problem, just updated the PR title to keep track of status.

**Comment by jackgerrits** [comment]
Hi @adityauser, we're planning on releasing VW 9 in early December. If you wanted to get this PR in to the release then there's still plenty of time for that. Given the WIP state here I am not sure what is left in terms of getting it ready.

**Comment by jackgerrits** [comment]
I'm going to go ahead and close this as it looks like it is no longer being worked on and not in a state where we know how to get it over the line. If you wish to pick this back in future then please feel free to reopen!

**Pull request closed without merging**
