### PR TITLE
Use std::exp instead of exp free function

### PR DESCRIPTION
**Pull request by jackgerrits**
This should resolve the rounding issues in #1706

### CODE REVIEW

**Comment by kumpera** [comment]
@JohnLangford is VW's numerical stability across OS/releases important?
If it is, we should consider whether to build and static link a custom libm.

**Comment by JohnLangford** [comment]
Yes.   The essential issue is that you need tests to verify that things are working and if the tests change across platforms it becomes a maintenance problem.

A custom libm seems like overkill?  Compared to little macros like this one.

**Comment by kumpera** [comment]
By custom I mean have a submodule to an existing implementation.
It's can be a problem in the sense that even basic functions like `exp` are implemented in different ways across OS and that could produce precision issues.

**Comment by JohnLangford** [comment]
I guess, the question is: are you thinking of proactively creating a library?  Or reactively?   If the former, there's an issue in that there are many functions we don't use.  If reactively, that informally exists---there are many little bits of code throughout that have a #ifdef depending on the OS.

**Pull request merged**
