### PR TITLE
cb_adf and cb_explore_adf: Setting --cb_type mtr as default

### PR DESCRIPTION
**Pull request by marco-rossi29**

### CODE REVIEW

**Comment by marco-rossi29** [comment]
@jackgerrits I discussed with @JohnLangford to make `mtr` the default cb_type. Some tests are failing since we change the default behavior. How do you suggest to proceed?

**Comment by JohnLangford** [comment]
Update the tests.  Note that RunTests has a flag to do this.

-John

**Comment by jackgerrits** [comment]
cb_algs.cc contains a default of `dr` and cb_explore_adf.cc contains a default if `ips`. Do we want to take this opportunity to normalize them all to `mtr`?

**Comment by JohnLangford** [comment]
mtr does not exist for non-adf.

**Comment by jackgerrits** [comment]
In that case should cb_explore_adf.cc be `mtr` and cb_algs.cc remain as `dr`?

**Comment by marco-rossi29** [comment]
I fixed all the errors in RunTests. However, now Travis is failing on Java Tests. @JohnLangford Is the a simple flag for the Java tests?

**Comment by JohnLangford** [comment]
I don't think so.

**Comment by marco-rossi29** [comment]
This PR is blocked on LGTM failing Java analysis

**Comment by jackgerrits** [comment]
@marco-rossi29 tests are now passing

**Comment by marco-rossi29** [comment]
This is ready to be squashed-merged!

**Comment by jackgerrits** [comment]
Thanks Marco!

**Pull request merged**
