### PR TITLE
Python: fix deprecated joblib

### PR DESCRIPTION
**Pull request by jackgerrits**
Fixes joblib being deprecated in sklearn, brings it in as dependency.

### CODE REVIEW

**Comment by jackgerrits** [comment]
@Scott-Graham-Bose Does this seem okay to you?

**Comment by JohnLangford** [comment]
This pull request **introduces 2 alerts** when merging 3146b37833d4595f9d8f20558ba3d6d66efb67f5 into da4271e3896fcfdb68b6dc1b880d4c754fac1699 - [view on LGTM.com](https://lgtm.com/projects/g/VowpalWabbit/vowpal_wabbit/rev/pr-ba0380dbda901678ce07862946fc43a73673a0d7)

**new alerts:**

* 2 for &#39;import \*&#39; may pollute namespace

---

**Warning** - Automated code review for VowpalWabbit/vowpal_wabbit will be disabled on October 1, 2019. You can avoid this by <a href="https://github.com/apps/lgtm-com/installations/new">installing the LGTM.com GitHub App</a>. Read about the <a href="https://lgtm.com/blog/announcing_github_apps_migration">benefits of migrating to GitHub Apps</a> in the blog.

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by jackgerrits** [comment]
This actually may be a bit confusing given the sklearn class is called `VW` and the non-sklearn one is `pyvw`.

Perhaps just bringing in the pyvw.py items?

**Comment by jackgerrits** [comment]
Thinking about this again it's not clear whether we want to force people to bring in both sklearn and normal interfaces. Going to scale this back to the joblib fix

**Pull request merged**
