### PR TITLE
build: use correct platform suffix for Python native shared library

### PR DESCRIPTION
**Pull request by jackgerrits**

### CODE REVIEW

**Comment by jackgerrits** [comment]
@ngam FYI

**Comment by ngam** [comment]
You mean before merging into master or by simply testing this exact PR? I can do both. 

I want to start a dev branch in the conda-forge vw feedstock for this sort of thing. I will get to it tonight --- that way we can test stuff down there without having to disrupt the stable flow and the outputs would go to a dev channel and so end users won't find it unless they go looking for it. It's a good strategy to test things

**Comment by jackgerrits** [comment]
> You mean before merging into master or by simply testing this exact PR? I can do both.

I just meant if it is possible to know if this unblocks the PyPy issue without needing to wait until a release tag is created and pushed

Dev channel sounds good!

**Comment by ngam** [comment]
Okay, I will do it soon :)

**Comment by jackgerrits** [comment]
Thanks so much. Appreciate all of the help so much by the way!

**Comment by ngam** [comment]
> @ngam is it possible to verify this works before the patch release?

can confirm!

https://github.com/conda-forge/vowpalwabbit-feedstock/pull/50

**Review by lalo — APPROVED** [review]

**Pull request merged**
