### PR TITLE
fix to make invert_hash work with bfgs (issue number 1891)

### PR DESCRIPTION
**Pull request by agroh1**
Fixes issue where models trained with bfgs could not invert the hash.

I copied the code from ftrl.cc which does do this correctly.  

There is also code in ftrl that does this for multipredict that I did not copy.  I was not sure when that was used.

### CODE REVIEW

**Comment by jackgerrits** [comment]
It does seem like the other base reductions are doing this operation in their predict function too.

@JohnLangford @marco-rossi29 Are you aware of any differences in the way invert_hash is done between 8.5.0 and 8.6.0? Was it previously done in one of the GD::* calls that are being done here?

**Comment by JohnLangford** [comment]
invert_hash is essentially done via the audit pipeline.  It's always functioned in this way.

**Comment by jackgerrits** [comment]
This block is present in the predict function of all base learners except bfgs though?
```
  if (audit)
      GD::print_audit_features(*(b.all), ec);
```

**Comment by JohnLangford** [comment]
This is an inconsistency.

-John

**Comment by jackgerrits** [comment]
Sounds good, going to merge this in as it fixes that.

**Pull request merged**
