### PR TITLE
Fixes nameerror in Contextual_Bandit_Examples

### PR DESCRIPTION
**Pull request by Smit-create**
#### Changes made
* python
  * Removed `i==1` and `j==1` to fix `NameError`

### CODE REVIEW

**Comment by jackgerrits** [comment]
Can you please clear the outputs to make the diff a bit more reasonable?

**Comment by Smit-create** [comment]
Should I clear the output of all the cells and then push the changes?

**Comment by jackgerrits** [comment]
Yes that would be good, thanks!

**Comment by Smit-create** [comment]
Thanks @jackgerrits

**Pull request merged**
