### PR TITLE
Small batch of cleanups to io_buff

### PR DESCRIPTION
**Pull request by kumpera**
As part of trying to make the IO stack modular, I'm trying to tame the design of io_buf in such a way that internals don't bleed all around.

This is a small step towards better abstracting the underlying data source and avoid some of the oddities we have when using it with non-file streams.

### CODE REVIEW

**Comment by JohnLangford** [comment]
This seems good, but something is barfing in the tests?

**Comment by kumpera** [comment]
I'll double check the test results tomorrow.

**Comment by palmerlao** [comment]
I think this question/drive-by suggestion may qualify as a small cleanup for `io_buf`, but if it isn't correct or doesn't fit here well, I'd be happy to open a separate PR. 

Is there a special use case for which it does not make sense to close all the file descriptors associated with an `io_buf` in the `io_buf`'s destructor? If not, I think it's safe to add `close_files` to the destructor since it's idempotent. Even better might be to have a separate RAII struct/class that holds a file descriptor instead of using the raw `int`s in `io_buf`, but maybe I'm glossing over some important details here?

**Comment by kumpera** [comment]
@palmerlao I can't answer that question precisely as I'm still going though the codebase learning how io_buf is used.

**Comment by kumpera** [comment]
@JohnLangford the tests are failing for me on master. I'll rather fix them first before blindly merging things

**Comment by JohnLangford** [comment]
@palmerlao I don't know of a use case where you can't close all files in the destructor.

**Comment by JohnLangford** [comment]
I'm confused about why this one is failing---it seems like such a simple patch.

**Comment by kumpera** [comment]
The crash is due to parser.cc : finalize_source modifying `io_buff::files` but using `io_buff::num_files()` to check its size. I discussed it with @jackgerrits and we believe the right cleanup here is to replace files/gz_files.

**Pull request closed without merging**
