### PR TITLE
Remove deprecated projects and old scripts

### PR DESCRIPTION
**Pull request by lokitoth**
* Removes Azure projects which have not been updated/supported in some time.
* Removes out-of-date README.Windows file (up-to-date content in Wiki)
* Removes out of date deploy/publish scripts

### CODE REVIEW

**Comment by JohnLangford** [comment]
This pull request **fixes 6 alerts** when merging 7240007e3251cf01d74ad3161baef10fa0b33065 into 36e44bc837c2818a238f3868f18963dc958d9cc5 - [view on LGTM.com](https://lgtm.com/projects/g/VowpalWabbit/vowpal_wabbit/rev/pr-c6dd4eb31f1acdbd4256383d717866cb3066c1e2)

**fixed alerts:**

* 3 for Rethrowing exception variable
* 2 for Missing Dispose call on local IDisposable
* 1 for Use of default ToString\(\)

---

This project has automated code review enabled, but doesn't use the <a href="https://github.com/apps/lgtm-com">LGTM GitHub App</a>. Migrate over by <a href="https://github.com/apps/lgtm-com/installations/new">installing the app</a>. Read about the <a href="https://lgtm.com/blog/announcing_github_apps_migration">benefits of migrating to GitHub Apps</a> in the blog.

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by jackgerrits** [comment]
Can you remove the link to the old windows readme in the current readme?

**Comment by JohnLangford** [comment]
This pull request **fixes 6 alerts** when merging 6c1037e48283df54c7d8d00ddaaddc4df8cdc252 into 36e44bc837c2818a238f3868f18963dc958d9cc5 - [view on LGTM.com](https://lgtm.com/projects/g/VowpalWabbit/vowpal_wabbit/rev/pr-50d106b0fa5f1e4e29c02c4a10a43c745cfb4c34)

**fixed alerts:**

* 3 for Rethrowing exception variable
* 2 for Missing Dispose call on local IDisposable
* 1 for Use of default ToString\(\)

---

This project has automated code review enabled, but doesn't use the <a href="https://github.com/apps/lgtm-com">LGTM GitHub App</a>. Migrate over by <a href="https://github.com/apps/lgtm-com/installations/new">installing the app</a>. Read about the <a href="https://lgtm.com/blog/announcing_github_apps_migration">benefits of migrating to GitHub Apps</a> in the blog.

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by JohnLangford** [comment]
This pull request **fixes 6 alerts** when merging c876ac6ae669e606eed5375960f7e67ec04b84c3 into 36e44bc837c2818a238f3868f18963dc958d9cc5 - [view on LGTM.com](https://lgtm.com/projects/g/VowpalWabbit/vowpal_wabbit/rev/pr-1fe25eb74055e933ddb7fc735896f932c51bee00)

**fixed alerts:**

* 3 for Rethrowing exception variable
* 2 for Missing Dispose call on local IDisposable
* 1 for Use of default ToString\(\)

---

This project has automated code review enabled, but doesn't use the <a href="https://github.com/apps/lgtm-com">LGTM GitHub App</a>. Migrate over by <a href="https://github.com/apps/lgtm-com/installations/new">installing the app</a>. Read about the <a href="https://lgtm.com/blog/announcing_github_apps_migration">benefits of migrating to GitHub Apps</a> in the blog.

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by JohnLangford** [comment]
My favorite kind of pull request.

**Comment by JohnLangford** [comment]
This pull request **fixes 6 alerts** when merging b22b59990c62d00c0f258fd0a47dffe9cbcb3015 into d36fcf11f4261aa2d139f46f8cdb37346bcef318 - [view on LGTM.com](https://lgtm.com/projects/g/VowpalWabbit/vowpal_wabbit/rev/pr-9b631352feaea7f65a81badaa7d65dd256ea0c63)

**fixed alerts:**

* 3 for Rethrowing exception variable
* 2 for Missing Dispose call on local IDisposable
* 1 for Use of default ToString\(\)

---

This project has automated code review enabled, but doesn't use the <a href="https://github.com/apps/lgtm-com">LGTM GitHub App</a>. Migrate over by <a href="https://github.com/apps/lgtm-com/installations/new">installing the app</a>. Read about the <a href="https://lgtm.com/blog/announcing_github_apps_migration">benefits of migrating to GitHub Apps</a> in the blog.

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Pull request merged**
