### PR TITLE
Change learner output action to be 1 indexed

### PR DESCRIPTION
**Pull request by cheng-tan**
Fix issue #1482

### CODE REVIEW

**Comment by JohnLangford** [comment]
I think we would rather change everything to be zero indexed?

**Comment by cheng-tan** [comment]
yes, that requires c++ layer changed to be zero index which is a breaking change. This is a temporary fix to make java API action index be consistent. Once we change everything to be zero indexed, this commit should be removed.

**Comment by jackgerrits** [comment]
I very much agree that indices need to be normalized to 0 based (but not in this PR). We will 100% need to bump the major version number though as it is a hard breaking change for existing data files and scripts that use this, and we may need a migration story in place.

**Comment by jackgerrits** [comment]
I've created an issue to track the larger piece of work about fixing the indexing properly.

#1841

**Comment by cheng-tan** [comment]
@jmorra and @deaktator Please take a look when you get a chance. There is an inconsistency for java API when calling `learn`, for input action needs to be 1-indexed and output is 0-indexed. This commit change the output to be 1-indexed as well for consistency. Everything will be changed to be 0-indexed when we are ready for the migration.

**Comment by JohnLangford** [comment]
It seems like we have three options before us:
(1) Leave as-is and document. 
(2) Shift everything to be 1-indexed and then shift everything to be 0-indexed.  
(3) Shift everything to be 0-indexed. 

I think we are in agreement that 0-indexed is better in the long term?  Given that, shouldn't we be preferring (3) over (2)?

**Comment by jon-morra-zefr** [comment]
This seems fine with me.  I'd favor consistency everywhere and then make the breaking change later.

**Comment by JohnLangford** [comment]
Closing this for now, since we want to avoid a double switch in the interface.

**Pull request closed without merging**
