### PR TITLE
build: Enable building Python library using VS2019

### PR DESCRIPTION
**Pull request by lokitoth**
* Enables user-supplied CMake generator --global-option
* Updates setup script to use Python setuptools to discover headers

### CODE REVIEW

**Review by jackgerrits — APPROVED** [review]

**Review by olgavrou — COMMENTED** [review]
Does this get exercised in a CI?

**Comment by lokitoth** [comment]
@olgavrou Yes, in multiple different OSes and target versions - so it spotted my typo around which cmake_generator variable I was using, and failed multiple times.

**Comment by olgavrou** [comment]
> @olgavrou Yes, in multiple different OSes and target versions - so it spotted my typo around which cmake_generator variable I was using, and failed multiple times.
> 
> Or do you mean whether we have a VS2019 CI? The answer to that is no, not at the moment.

Yes I meant in our existing CI collection, @jackgerrits added [this](https://github.com/VowpalWabbit/vowpal_wabbit/blob/master/.github/workflows/build_windows_cmake.yml#L53) relatively recently would it be worth building this there?

**Comment by lokitoth** [comment]
@olgavrou Honestly, probably not really. We should check whether it is reasonable to move to VS 2019 for building Python by default and simply migrate to it. If it does not reduce Windows version compatibility to a place we do not want it. The goal of this PR was simply to make it possible to inject a custom toolchain.

**Comment by olgavrou** [comment]
> @olgavrou Honestly, probably not really. We should check whether it is reasonable to move to VS 2019 for building Python by default and simply migrate to it. If it does not reduce Windows version compatibility to a place we do not want it. The goal of this PR was simply to make it possible to inject a custom toolchain.

Fair enough

**Review by olgavrou — APPROVED** [review]

**Pull request merged**
