### PR TITLE
vw-hyperopt. Passing additional command when training and validating

### PR DESCRIPTION
**Pull request by whitish**
Basically sometimes you need to explicitly pass additional parameters like '--keep' when training/validating the model.

### CODE REVIEW

**Comment by lokitoth** [comment]
Hi @whitish,

Thank you for the work you are putting into the vw-hyperopt tool. If I understood @arielf correctly from #1955, the request was to squash some of the commits together that have no change between them to make it easier to identify the critical changes / commits.

Let me know if I can help with that in any way.

**Comment by whitish** [comment]
Squashed.

**Comment by jackgerrits** [comment]
It looks to me like this is a subset of the changes in #1955. But it seems like some of those other changes were needed.

Can you please clarify why there are two PRs and can you close the one that is not required anymore?

**Comment by lokitoth** [comment]
@jackgerrits I am guessing the new PR was created because of a miscommunication between @arielf and @whitish re: squashing commits. I would close #1955 and continue here.

**Comment by whitish** [comment]
@lokitoth , Jacob, could you please take a quick look on the log of failed checks. I am not seeing any errors related to the RP.

**Comment by lokitoth** [comment]
@whitish It looks like the Windows Azure Pipelines CI failed due to a sporadic test failure. (Logged as #1978). The Mac OS issue is known and under investigation - that is why it is not a required check, yet.

I am not sure why the python stage of the Travis CI build is failing. Maybe @peterychang has more insight?

**Comment by jackgerrits** [comment]
Build failures were sporadic test issues, can this be merged?

**Comment by lokitoth** [comment]
> Build failures were sporadic test issues, can this be merged?

I think @arielf was reviewing the previous incarnation of the PR

**Comment by jackgerrits** [comment]
@arielf, does this PR resolve your previous comments?

**Comment by arielf** [comment]
Thanks @jackgerrits. Looks good. (just catching up :)

**Pull request merged**
